% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3a (COMSOL 3.3.0.511, $Date: 2007/02/02 19:05:58 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 511;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007/02/02 19:05:58 $';
fem.version = vrsn;

% Geometry
g1=rect2('1.e-3','2.e-2','base','center','pos',{'0','1.e-2'},'rot','0');
g2=rect2('1.e-2','1.e-2','base','center','pos',{'0','-5.e-3'},'rot','0');
g3=rect2('0.01','5.e-3','base','center','pos',{'0','-0.0025'},'rot','0');
g4=rect2('0.01','0.010','base','center','pos',{'0','-0.005'},'rot','0');

% Analyzed geometry
clear s
s.objs={g1,g4};
s.name={'R1','R2'};
s.tags={'g1','g4'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Create mapped quad mesh
fem.mesh=meshmap(fem, ...
                 'edgegroups',{{[2],[9],[8, 5, 3],[1]},{}}, ...
                 'edgelem',{4,[0 0.02 0.04 0.06 0.08 0.1 0.12 0.14 0.16 0.18 0.2 0.22 0.24 0.26 0.28 0.3 0.32 0.34 0.36 0.38 0.4 0.42 0.44 0.46 0.48 0.5 0.52 0.54 0.56 0.58 0.6 0.62 0.64 0.66 0.68 0.7 0.72 0.74 0.76 0.78 0.8 0.82 0.84 0.86 0.88 0.9 0.92 0.94 0.96 0.98 1],5,[0 0.3333333333333333 0.6666666666666666 1]}, ...
                 'hauto',5);

% Create mapped quad mesh
fem.mesh=meshmap(fem, ...
                 'edgegroups',{{[2],[9],[8, 5, 3],[1]},{}}, ...
                 'edgelem',{1,[0 0.025 0.05 0.075 0.1 0.125 0.15 0.175 0.2 0.225 0.25 0.275 0.3 0.325 0.35 0.375 0.4 0.425 0.45 0.475 0.5 0.525 0.55 0.575 0.6 0.625 0.65 0.675 0.7 0.725 0.75 0.775 0.8 0.825 0.85 0.875 0.9 0.925 0.95 0.975 1],2,[0 0.025 0.05 0.075 0.1 0.125 0.15 0.175 0.2 0.225 0.25 0.275 0.3 0.325 0.35 0.375 0.4 0.425 0.45 0.475 0.5 0.525 0.55 0.575 0.6 0.625 0.65 0.675 0.7 0.725 0.75 0.775 0.8 0.825 0.85 0.875 0.9 0.925 0.95 0.975 1],4,[0 0.0125 0.025 0.0375 0.05 0.0625 0.075 0.0875 0.1 0.1125 0.125 0.1375 0.15 0.1625 0.175 0.1875 0.2 0.2125 0.225 0.2375 0.25 0.2625 0.275 0.2875 0.3 0.3125 0.325 0.3375 0.35 0.3625 0.375 0.3875 0.4 0.4125 0.425 0.4375 0.45 0.4625 0.475 0.4875 0.5 0.5125 0.525 0.5375 0.55 0.5625 0.575 0.5875 0.6 0.6125 0.625 0.6375 0.65 0.6625 0.675 0.6875 0.7 0.7125 0.725 0.7375 0.75 0.7625 0.775 0.7875 0.8 0.8125 0.825 0.8375 0.85 0.8625 0.875 0.8875 0.9 0.9125 0.925 0.9375 0.95 0.9625 0.975 0.9875 1],5,[0 0.25 0.5 0.75 1]}, ...
                 'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000};
bnd.ind = [2,1,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'mises_smps','cont','internal','unit','Pa'}, ...
         'trimap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: von Mises stress [Pa]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.023745386923123772,0.023745386923123772,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: x-displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.0213124995236285,0.0213124995236285,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: Disp. amplitude y-dir. [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021093749528517947,0.021093749528517947,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: Disp. amplitude x-dir. [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02121874952572398,0.02121874952572398,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02121874952572398,0.02121874952572398,-0.011499999742954969,0.02149999951943755,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.024374999455176294,0.024374999455176294,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smps(3)=110    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021531249518739054,0.021531249518739054,-0.011499999742954969,0.02149999951943755,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[10000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'title','freq_smps(1)=10000    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021531249518739054,0.021531249518739054,-0.011499999742954969,0.02149999951943755,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[1.806e5], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'title','freq_smps(1)=1.806e5    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021093749528517947,0.021093749528517947,-0.011499999742954969,0.02149999951943755,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[1.8e5], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'title','freq_smps(1)=1.8e5    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021093749528517954,0.021093749528517954,-0.011598360396494152,0.021598360172976724,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmePlaneStress';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smps';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1,1];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','v'}, ...
                  'outcomp',{'u','v'}, ...
                  'pname','freq_smps', ...
                  'plist',[3e5], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u_amp_smps','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'title','freq_smps(1)=3e5    Surface: Disp. amplitude x-dir. [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.021093749528517954,0.021093749528517954,-0.011598360396494152,0.021598360172976724,-1,1]);
