% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3a (COMSOL 3.3.0.511, $Date: 2007/02/02 19:05:58 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 511;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007/02/02 19:05:58 $';
fem.version = vrsn;

% Geometry
g1=rect2('1.e-3','2.e-2','base','corner','pos',{'0','0'},'rot','0');
carr={curve2([-0.0040,-0.0040],[0.02,0],[1,1])};
g2=geomcoerce('curve',carr);

% Analyzed geometry
clear c s
c.objs={g2};
c.name={'B1'};
c.tags={'g2'};

s.objs={g1};
s.name={'R1'};
s.tags={'g1'};

fem.draw=struct('c',c,'s',s);
fem.geom=geomcsg(fem);
g1=move(g1,[0.0010,0]);
gg=geomedit(g2);
gg{1}=beziercurve2([0,0],[0.02,0],[1,1]);
g3=geomedit(g2,gg);

% Analyzed geometry
clear c
c.objs={g3};
c.name={'B1'};
c.tags={'g3'};

fem.draw=struct('c',c);
fem.geom=geomcsg(fem);
g4=rect2('1.e-2','1.e-2','base','corner','pos',{'-5.e-3','-1.e-2'},'rot','0');

% Analyzed geometry
clear c s
c.objs={g3};
c.name={'B1'};
c.tags={'g3'};

s.objs={g4};
s.name={'R1'};
s.tags={'g4'};

fem.draw=struct('c',c,'s',s);
fem.geom=geomcsg(fem);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {1.e-3,0.1};
bnd.ind = [2,2,2,1,2,2];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000};
bnd.ind = [2,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.009816671776424861,0.010816671823922312,-0.017949675520645976,0.0047805525919316,-1,1]);

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01184374973527156,0.01184374973527156,-0.011499999742954969,0.02149999951943755,-1,1]);

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.usage = {0,1};
bnd.dampingtype = {'nodamping','Rayleigh'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000};
bnd.ind = [2,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.014856088228826154,0.014856088228826154,-0.011499999742954969,0.02149999951943755,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.usage = {0,1};
bnd.dampingtype = {'nodamping','Rayleigh'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000};
bnd.ind = [2,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01184374973527156,0.01184374973527156,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'disp_smpn','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: Total displacement [m]   Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01184374973527156,0.01184374973527156,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'disp_smpn','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: Total displacement [m]   Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.009078313050095935,0.009078313050095935,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.009078313050095935,0.009078313050095935,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: x-displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.008978915461956196,0.008978915461956196,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'lindata',{'v','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: y-displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.00901204799133611,0.00901204799133611,-0.011499999742954969,0.02149999951943755,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'v','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: y-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.006493975758462785,0.006162650464663664,-0.016261095490540438,0.006911698109154311,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,1.7e-12};
bnd.A = {0.01,2.e-5};
bnd.usage = {0,1};
bnd.dampingtype = 'nodamping';
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000};
bnd.ind = [2,1,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'v','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: y-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.011686367615139009,0.011355042321339888,-0.012577363649012036,0.010227966267625888,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,1.7e-12};
bnd.A = {0.01,2.e-5};
bnd.usage = {0,1};
bnd.dampingtype = 'nodamping';
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,1000,0};
bnd.constrcond = {'free','free','displacement'};
bnd.Hy = {0,0,1};
bnd.ind = [2,3,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'v','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: y-displacement [m]   Boundary: y-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.012379152252076735,0.012047826958277615,-0.01701305008270246,0.007163652701316294,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.00707954892442045,0.006748223630621329,-0.012969257565859456,0.013119860184473276,-1,1]);
