% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3a (COMSOL 3.3.0.511, $Date: 2007/02/02 19:05:58 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 511;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007/02/02 19:05:58 $';
fem.version = vrsn;

% Geometry
g1=curve2([0,0],[0,0.04]);

% Analyzed geometry
clear c
c.objs={g1};
c.name={'B1'};
c.tags={'g1'};

fem.draw=struct('c',c);
fem.geom=geomcsg(fem);
g2=square2('1.e-2','base','center','pos',{'0','5.e-3'},'rot','0');
g3=square2('0.01','base','center','pos',{'0','-0.0050'},'rot','0');

% Analyzed geometry
clear c s
c.objs={g1};
c.name={'B1'};
c.tags={'g1'};

s.objs={g3};
s.name={'SQ1'};
s.tags={'g3'};

fem.draw=struct('c',c,'s',s);
fem.geom=geomcsg(fem);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% Refine mesh
fem.mesh=meshrefine(fem, ...
                    'mcase',0, ...
                    'rmethod','regular');

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,'1.e-3^3*1.e-3/12'};
bnd.A = {0.01,'1.e-3*1.e-3'};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[90:10:110], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'solnum','end', ...
         'title','freq_smeulip(3)=110    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02476014612565621,0.02476014612565621,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,'1.e-3^3*1.e-3/12'};
bnd.A = {0.01,'1.e-3*1.e-3'};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'title','freq_smeulip(1)=1000    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01994791547767818,0.01994791547767818,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.020156248798593877,0.020156248798593877,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,4.e-2};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: y-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01588509222087653,0.01588509222087653,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'v','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: y-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015201862447935602,0.015201862447935602,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.020531187860066427,0.020531187860066427,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[100], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=100    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01588509222087653,0.01588509222087653,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,2.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[100], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=100    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smpn', ...
                  'plist',[100], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smpn(1)=100    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='eigen';
appl.prop = prop;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
appl.var = {'freq','100'};
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femeig(fem, ...
               'solcomp',{'u','th','v'}, ...
               'outcomp',{'u','th','v'}, ...
               'rowscale','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',1, ...
         'title','eigfreq_smeulip(1)=0    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02470940812130036,0.02470940812130036,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',3, ...
         'title','eigfreq_smeulip(3)=3228.973465    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.017615460797426208,0.017615460797426208,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='eigen';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
appl.var = {'freq','100'};
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femeig(fem, ...
               'solcomp',{'u','th','v'}, ...
               'outcomp',{'u','th','v'}, ...
               'rowscale','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',1, ...
         'title','eigfreq_smeulip(1)=0    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',2, ...
         'title','eigfreq_smeulip(2)=788.250516    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.017781123438154356,0.017781123438154356,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01816252479734628,0.01816252479734628,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='eigen';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
appl.var = {'freq','100'};
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015657348963229553,0.015657348963229553,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015657348963229553,0.015657348963229553,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='eigen';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
appl.var = {'freq','100'};
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='eigen';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
appl.var = {'freq','100'};
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femeig(fem, ...
               'solcomp',{'u','th','v'}, ...
               'outcomp',{'u','th','v'}, ...
               'rowscale','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',1, ...
         'title','eigfreq_smeulip(1)=0    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015657348963229553,0.015657348963229553,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'solnum',2, ...
         'title','eigfreq_smeulip(2)=561.550658    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.017781123438154356,0.017781123438154356,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip,freq_smpn', ...
                  'plist',[1000,1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip,freq_smpn(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.01742235920999361,0.01742235920999361,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.016055899664111757,0.016055899664111757,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'deformscale',1, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015657348963229553,0.015657348963229553,-0.01249999962747097,0.042499997094273566,-1,1]);

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.015657348963229553,0.015657348963229553,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,4.e-2};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'rowscale','off', ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'tridata',{'u','cont','internal','unit','m'}, ...
         'trimap','jet(1024)', ...
         'deformsub',{'u','v'}, ...
         'lindata',{'u','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Surface: x-displacement [m]   Boundary: x-displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.02778467743293099,0.02778467743293099,-0.01249999962747097,0.042499997094273566,-1,1]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.constrcond = {'free','norot'};
pnt.ind = [1,1,2,1,1,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = {0.1,1.e-3};
bnd.Iyy = {8.33e-6,8.33e-14};
bnd.A = {0.01,1.e-6};
bnd.usage = {0,1};
bnd.dampingtype = {'Rayleigh','nodamping'};
bnd.ind = [1,1,1,2,1,1];
appl.bnd = bnd;
fem.appl{1} = appl;

% Application mode 2
clear appl
appl.mode.class = 'SmePlaneStrain';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smpn';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear bnd
bnd.Fx = {0,0,-1000};
bnd.constrcond = {'free','displacement','free'};
bnd.Hy = {0,1,0};
bnd.ind = [3,2,1,1,1,1];
appl.bnd = bnd;
clear equ
equ.dampingtype = 'nodamping';
equ.thickness = 1.e-3;
equ.ind = [1];
appl.equ = equ;
fem.appl{2} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);
