% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3a (COMSOL 3.3.0.511, $Date: 2007/02/02 19:05:58 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 511;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007/02/02 19:05:58 $';
fem.version = vrsn;

% Geometry
g1=curve2([0,0],[0,0.04]);

% Analyzed geometry
clear c
c.objs={g1};
c.name={'B1'};
c.tags={'g1'};

fem.draw=struct('c',c);
fem.geom=geomcsg(fem);

% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hauto',5);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'SmeInPlaneEulerBeam';
appl.module = 'SME';
appl.gporder = 6;
appl.cporder = 1;
appl.assignsuffix = '_smeulip';
clear prop
prop.analysis='freq';
appl.prop = prop;
clear pnt
pnt.Fx = {0,.01};
pnt.constrcond = {'free','norot'};
pnt.m = {0,7.85e-4};
pnt.ind = [2,1];
appl.pnt = pnt;
clear bnd
bnd.heightz = 1.e-3;
bnd.Iyy = 8.33e-14;
bnd.A = 1.e-6;
bnd.dampingtype = 'nodamping';
bnd.ind = [1];
appl.bnd = bnd;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femstatic(fem, ...
                  'solcomp',{'u','th','v'}, ...
                  'outcomp',{'u','th','v'}, ...
                  'pname','freq_smeulip', ...
                  'plist',[1000], ...
                  'oldcomp',{}, ...
                  'nonlin','off');

% Save current fem structure for restart purposes
fem0=fem;

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'title','freq_smeulip(1)=1000    Boundary: Total displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.022227742774392753,0.022227742774392753,-0.0019999999552965165,0.041999999061226846,-1,1]);

% Plot solution
postplot(fem, ...
         'lindata',{'disp_smeulip','cont','internal','unit','m'}, ...
         'linmap','jet(1024)', ...
         'deformbnd',{'u','v'}, ...
         'title','freq_smeulip(1)=1000    Boundary: Total displacement [m]   Deformation: Displacement [m]', ...
         'refine',1, ...
         'axisvisible','off', ...
         'axis',[-0.016124999639578166,0.016124999639578166,-0.0019999999552965165,0.041999999061226846,-1,1]);

% Integrate
I1=postint(fem,'u', ...
           'unit','m', ...
           'dl',[1], ...
           'edim',0);

% Integrate
I2=postint(fem,'u', ...
           'unit','m', ...
           'dl',[2], ...
           'edim',0);
