% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.3a (COMSOL 3.3.0.511, $Date: 2007/02/02 19:05:58 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.3';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 511;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2007/02/02 19:05:58 $';
fem.version = vrsn;

% Geometry
g1=sphere3('1','pos',{'-2','-2','0'},'axis',{'0','0','1'},'rot','0');
g2=sphere3('1','pos',{'2','2','0'},'axis',{'0','0','1'},'rot','0');
g3=geomcomp({g1,g2},'ns',{'SPH1','SPH2'},'sf','SPH1+SPH2','face','none','edge','all');
g4=sphere3('1','pos',{'-2','2','0'},'axis',{'0','0','1'},'rot','0');
g5=geomcomp({g3,g4},'ns',{'CO1','SPH1'},'sf','SPH1+CO1','face','none','edge','all');
g6=sphere3('0.5','pos',{'1','-1','0'},'axis',{'0','0','1'},'rot','0');
g7=sphere3('0.5','pos',{'-4','-4','0'},'axis',{'0','0','1'},'rot','0');

% Analyzed geometry
clear s
s.objs={g5,g6,g7};
s.name={'CO2','SPH4','SPH5'};
s.tags={'g5','g6','g7'};

fem.draw=struct('s',s);
[g,st] = geomcsg(fem);
[SubInd,s0] = find(st)    
fem.geom = geomcsg(fem);


% (Default values are not included)
a = 2
% Application mode 1
clear appl
appl.mode.class = 'SmeSolid3';
appl.module = 'SME';
appl.gporder = 4;
appl.cporder = 2;
appl.assignsuffix = '_smsld';

clear equ
equ.E = { 2.0e11, 1.0e11, 4.e5 };
equ.ind(SubInd) = s0;
appl.equ = equ;

fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;
clear units;
units.basesystem = 'SI';
fem.units = units;

% Multiphysics
fem=multiphysics(fem);
